### ISSUE TITLE
editplantilla

### ISSUE THREAD

**Issue by nathalysilva23** [hayderrojas84/trabajo_grado_mod_1#15]
Edición y modificación de la plantilla

**Comment by Hamilton17** [comment]
# Plantilla de Toma de Datos para Plan Nutricional

## Información Personal
- **Nombre del Usuario**:
- **Edad**:
- **Género**:
- **Peso (kg)**:
- **Altura (cm)**:
- **Actividad Física**:
   - [ ] Sedentario (poco o ningún ejercicio)
   - [ ] Moderado (ejercicio ligero o actividad física moderada)
   - [ ] Activo (ejercicio regular o actividad física intensa)
   - [ ] Muy Activo (ejercicio intenso o actividad física extenuante)

## Objetivos Nutricionales
- **Objetivo de Peso**:
   - [ ] Pérdida de Peso
   - [ ] Mantenimiento de Peso
   - [ ] Ganancia de Peso
- **Cantidad de Pérdida o Ganancia de Peso Deseada (si es aplicable)**:
- **Objetivos de Nutrición (por ejemplo, mejorar la energía, ganar masa muscular, mejorar la salud digestiva, etc.)**:

## Preferencias Alimentarias
- **Restricciones Dietéticas (alergias, intolerancias, vegetarianismo, veganismo, etc.)**:
- **Alimentos Favoritos**:
- **Alimentos que No Te Gustan**:

## Hábitos Alimentarios
- **Número de Comidas al Día**:
- **Horario de Comidas**:
- **Consumo de Agua Diario (vasos o litros)**:
- **Consumo de Alcohol**:
   - [ ] Sí
   - [ ] No
- **Consumo de Tabaco o Nicotina**:
   - [ ] Sí
   - [ ] No

## Información Adicional
- **Condiciones Médicas Relevantes (por ejemplo, diabetes, hipertensión, enfermedades cardíacas, etc.)**:
- **Medicamentos Actuales**:
- **Suplementos Alimenticios Actuales (si los hay)**:
- **Observaciones Adicionales**:

## Metodología de Seguimiento
- **Frecuencia de Seguimiento Nutricional**:
   - [ ] Semanal
   - [ ] Quincenal
   - [ ] Mensual

## Notas Finales
Asegúrate de que los datos proporcionados por el usuario sean completos y precisos para crear un plan nutricional efectivo y seguro. Considera trabajar en estrecha colaboración con un profesional de la salud o un dietista registrado para garantizar que el plan sea adecuado para las necesidades individuales del usuario.
